### PR TITLE
support for azurestack

### PR DESCRIPTION
**Pull request by rakku-ms**
test against 
azure: https://github.com/rakku-ms/get-keyvault-secrets/actions/runs/292243295
azurestack: https://github.com/rakku-ms/get-keyvault-secrets/actions/runs/292243294

### CODE REVIEW

**Comment by rakku-ms** [comment]
@bganapa @sarathys @N-Usha @asranja please review
@garvitarai FYI

**Comment by asranja** [comment]
Few suggestions:
1. We can use `az cloud show` to get the current cloud environment. With this, we can remove the environment parameter passed in the yml file.
2. Can we add some common logic here in the [authorizer](https://github.com/microsoft/pipelines-appservice-lib/blob/master/packages/webclient/src/Authorizer/AzureCLIAuthorizer.ts) so that it can be available to all azure actions. 

@rakku-ms Since we already added suffixes while registering AzureStack cloud. Can we not get them directly using this [method](https://github.com/microsoft/pipelines-appservice-lib/blob/de6f6f44fc0c81abb72e138d710216145947ef1f/packages/webclient/src/Authorizer/AzureCLIAuthorizer.ts#L26).

**Comment by rakku-ms** [comment]
@asranja please review this PR in Authorizer code: https://github.com/microsoft/pipelines-appservice-lib/pull/31

When is your team planning to update the azure-actions-webclient version?

"dependencies": {
    "@actions/core": "1.1.3",
    "azure-actions-webclient": "1.0.1"
  },

**Comment by rakku-ms** [comment]
@asranja this repo is using the older version of Authorizer code which may take sometime to upgrade. So I have added the 'executeAzCliCommand' function in the keyvault code itself as a workaround for now. We don't need the additional parameter 'environment' now for this keyvault action. Please review and maybe create separate branch for AzureStack just like we did for login action.

**Review by romil07 — APPROVED** [review]

**Comment by rakku-ms** [comment]
@narula0781, @chandrasekharmudili any update regarding this PR? are you planning to merge this to master or create a separate beta branch for AzureStack?

**Comment by ds-ms** [comment]
@rakku-ms could you update your branch and fix the merge conflicts?

**Review by ds-ms — APPROVED** [review]

**Comment by rakku-ms** [comment]
@ds-ms I fixed all merge conflicts with the master. Can you please merge this PR?

Successful runs:
AzureStack - https://github.com/rakku-ms/get-keyvault-secrets/runs/2197860526?check_suite_focus=true
AzureCloud - https://github.com/rakku-ms/get-keyvault-secrets/runs/2197860507?check_suite_focus=true

**Pull request merged**
